### ISSUE TITLE
Lualine Theme Not Setting

### ISSUE THREAD

**Issue by jonathan-raines** [Pocco81/Catppuccino.nvim#30]
Good afternoon!

I'm loving this theme but having some issues. I cannot get this theme to set in lualine following the repos instructions. Here is my current config for both plugins. I can change the lualine theme to any of it's builtin themes but this one isn't working.

  ```
use {
    'shadmansaleh/lualine.nvim',
    config = function()
      require('lualine').setup {
        options = {
          component_separators = '',
          section_separators = '',
          theme = 'catppuccino',
        },
      }
    end,
  }
````
```
  use {
    'Pocco81/Catppuccino.nvim',
    config = function()
      require('catppuccino').setup {
        colorscheme = 'dark_catppuccino',
        term_colors = true,
        integrations = {
          gitsigns = true,
          which_key = true,
          telescope = true,
          nvimtree = {
            enabled = true,
          },
        },
      }
      vim.cmd [[colorscheme catppuccino]]
    end,
  }
```
Thank you for any help or insight you can provide!

**Comment by Pocco81** [comment]
Hey! In order for lualina to pick `catppuccino` it must be loaded after Catppuccino.nvim. I noticed that you are using Packer.nvim, and for that one you can use the `after` setting to make a plugin load only after another plugin, so in your case it'd look like:
```lua
 use {
    'Pocco81/Catppuccino.nvim',
    config = function()
     -- config...
   end,
 }

use {
  'shadmansaleh/lualine.nvim',
  after = "Catppuccino.nvim",
  config = function()
    -- config
  end,
}
```

Should be working afterwards. Cheers :)

**Comment by jonathan-raines** [comment]
@Pocco81 it's still not working. I made sure to also run `:PackerSync` after making the changes also. Here are the updated configs

```
  use {
    'shadmansaleh/lualine.nvim',
    config = function()
      require('lualine').setup {
        options = {
          component_separators = '',
          section_separators = '',
          theme = 'catppuccino',
        },
      }
    end,
    after = 'Catppuccino.nvim',
    requires = { 'nvim-lua/plenary.nvim' },
  }
```
```
  use {
    'Pocco81/Catppuccino.nvim',
    config = function()
      require('catppuccino').setup {
        colorscheme = 'dark_catppuccino',
        term_colors = true,
        integrations = {
          gitsigns = true,
          which_key = true,
          telescope = true,
          nvimtree = {
            enabled = true,
          },
        },
      }
      vim.cmd [[colorscheme catppuccino]]
    end,
  }
```

**Comment by Pocco81** [comment]
Let me try it. In the mean time, why don't you enable the integration for gitsigns too? :)

**Comment by Pocco81** [comment]
Whoops my bad! it was supposed to be the other way around sorry! _Catppuccino_ should be loaded **after** _lualine_. It should look like this (I'm using Neon Latte btw):

![image](https://user-images.githubusercontent.com/58336662/132108928-cab25811-027c-48a1-9504-218872ef7563.png)
